### ISSUE TITLE
Cannot train model on GPU (only CPU) using simpletransformers

### ISSUE THREAD

**Issue by timpal0l** [ltgoslo/NorBERT#1]
**Describe the bug**
I cannot use the model after it has been trained, it only predicts one of two classes. And the probabilites are set to `nan`. 
I recieve thousands of warning such as:

@akutuzov 
edit: if `model_name = "ltgoslo/norbert"`is set to any other hugginface model e.g `KB/bert-base-swedish-cased` it works fine.

```
Saving vocabulary to outputs/vocab.txt: vocabulary indices are not consecutive. Please check that the vocabulary is not corrupted!
Saving vocabulary to outputs/vocab.txt: vocabulary indices are not consecutive. Please check that the vocabulary is not corrupted!
Saving vocabulary to outputs/vocab.txt: vocabulary indices are not consecutive. Please check that the vocabulary is not corrupted!
```
There seems to be something that is broken in the vocabulary, since this code works fine with any other Bert model on huggingface.

```
>>> model.predict(["Hejsan hur är läget?"])
([0], array([[nan, nan]]))
```
**To Reproduce**
```
import pandas as pd
from simpletransformers.classification import ClassificationModel

df = pd.read_csv('/home/norway_sentiment.csv')

train_df = pd.DataFrame(df[0:8000])
eval_df = pd.DataFrame(df[8000:])

train_args = {
    'reprocess_input_data': True,
    'overwrite_output_dir': True,
#    'evaluate_during_training': True,
    'max_seq_length': 128,
    'num_train_epochs': 1,
#    'evaluate_during_training_steps': 100,
    'train_batch_size': 64,
    'n_gpu': 1,
}

model_name = "ltgoslo/norbert"

model = ClassificationModel('bert', model_name, args=train_args, cuda_device=1)
model.train_model(train_df)
result, model_outputs, wrong_predictions = model.eval_model(eval_df)
```

**Expected behavior**
`model.eval_model(eval_df)`should report metrics.

**Error**
```
/home/tim/anaconda3/envs/transformers-source/lib/python3.7/site-packages/sklearn/metrics/_classification.py:870: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
Traceback (most recent call last):
  File "eval_sent.py", line 28, in <module>
    result, model_outputs, wrong_predictions = model.eval_model(eval_df)
  File "/home/tim/anaconda3/envs/transformers-source/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 911, in eval_model
    eval_df, output_dir, multi_label=multi_label, verbose=verbose, silent=silent, wandb_log=wandb_log, **kwargs
  File "/home/tim/anaconda3/envs/transformers-source/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 1079, in evaluate
    result, wrong = self.compute_metrics(preds, model_outputs, out_label_ids, eval_examples, **kwargs)
  File "/home/tim/anaconda3/envs/transformers-source/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 1285, in compute_metrics
    fpr, tpr, thresholds = roc_curve(labels, scores)
  File "/home/tim/anaconda3/envs/transformers-source/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/tim/anaconda3/envs/transformers-source/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 914, in roc_curve
    y_true, y_score, pos_label=pos_label, sample_weight=sample_weight)
  File "/home/tim/anaconda3/envs/transformers-source/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 697, in _binary_clf_curve
    assert_all_finite(y_score)
  File "/home/tim/anaconda3/envs/transformers-source/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/tim/anaconda3/envs/transformers-source/lib/python3.7/site-packages/sklearn/utils/validation.py", line 124, in assert_all_finite
    _assert_all_finite(X.data if sp.issparse(X) else X, allow_nan)
  File "/home/tim/anaconda3/envs/transformers-source/lib/python3.7/site-packages/sklearn/utils/validation.py", line 106, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```
**Desktop (please complete the following information):**
 - Ubuntu 20.04, CUDA Version: 11.0, GeForce GTX Titan X

**Comment by akutuzov** [comment]
Hi,

We test NorBERT using the HuggingFace [Transformers](https://github.com/huggingface/transformers) library. You seem to be using `simpletransformers`, which is less mainstream.

Can you provide steps to reproduce the error with the `Transformers`?

**Comment by oepen** [comment]
does that mean the developers of NorBERT do not currently want to support use of the model using the `simpletransformers` library?

**Comment by akutuzov** [comment]
@oe Not necessarily. 
It just means we had not encountered any issues like that with `Transformers`. To find the source of the problem, it could be useful to first check whether the problem exists in `Transformers` as well, or is ts `simpletransformers`-specific.

**Comment by timpal0l** [comment]
@akutuzov Thanks for your reply! I have not tried with the Transformers library. Do you have any code snippet I could try for binary classification with PyTorch?

Would be so greatful if it could work in simpletransformers thou, the rest of the huggingface models do work there.

**Comment by akutuzov** [comment]
@timpal0l I've just ran a simple classification task using NorBert and `simpletransformers`. 
It went OK, in the sense that the classifier was trained and I received meaningful predictions:

```
In [24]: result, model_outputs, wrong_predictions = model.eval_model(test_data) 
INFO:simpletransformers.classification.classification_model:{'mcc': 0.3311525398694757, 'tp': 37, 'tn': 3, 'fp': 7, 'fn': 2, 'auroc': 0.7461538461538462, 'auprc': 0.9173416742981831, 'eval_loss': 0.568481581551688}
In [26]: predictions                                                                                                                                                                         
Out[26]: [0]
In [27]: raw_outputs                                                                                                                                                                         
Out[27]: array([[0.43196979, 0.36896741]])
```

Can you try to re-download NorBert? 

However, I confirm the existence of "Saving vocabulary to outputs/vocab.txt: vocabulary indices are not consecutive. Please check that the vocabulary is not corrupted" warnings, although they do not seem to influence the result much. 
Investigating it now.

**Comment by timpal0l** [comment]
> @timpal0l I've just ran a simple classification task using NorBert and `simpletransformers`.
> It went OK, in the sense that the classifier was trained and I received meaningful predictions:
> 
> ```
> In [24]: result, model_outputs, wrong_predictions = model.eval_model(test_data) 
> INFO:simpletransformers.classification.classification_model:{'mcc': 0.3311525398694757, 'tp': 37, 'tn': 3, 'fp': 7, 'fn': 2, 'auroc': 0.7461538461538462, 'auprc': 0.9173416742981831, 'eval_loss': 0.568481581551688}
> In [26]: predictions                                                                                                                                                                         
> Out[26]: [0]
> In [27]: raw_outputs                                                                                                                                                                         
> Out[27]: array([[0.43196979, 0.36896741]])
> ```
> 
> Can you try to re-download NorBert?
> 
> However, I confirm the existence of "Saving vocabulary to outputs/vocab.txt: vocabulary indices are not consecutive. Please check that the vocabulary is not corrupted" warnings, although they do not seem to influence the result much.
> Investigating it now.

That is interesting. Could you provide me the full script and your library versions / cuda driver / os version. I have tried on various machines, with all the latest libraries. 

```
from simpletransformers.classification import ClassificationModel, ClassificationArgs
import pandas as pd
import logging


logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)

# Preparing train data
train_data = [
    ["Aragorn was the heir of Isildur", 1],
    ["Frodo was the heir of Isildur", 0],
]
train_df = pd.DataFrame(train_data)
train_df.columns = ["text", "labels"]

# Preparing eval data
eval_data = [
    ["Theoden was the king of Rohan", 1],
    ["Merry was the king of Rohan", 0],
]
eval_df = pd.DataFrame(eval_data)
eval_df.columns = ["text", "labels"]

# Optional model configuration
model_args = ClassificationArgs(num_train_epochs=1)

# Create a ClassificationModel
model = ClassificationModel(
    "bert", "ltgoslo/norbert", args=model_args
)

# Train the model
model.train_model(train_df)

# Evaluate the model
result, model_outputs, wrong_predictions = model.eval_model(eval_df)

# Make predictions with the model
predictions, raw_outputs = model.predict(["Sam was a Wizard"])
```

I note that even the running loss during training is set to `Running Loss:       nan`

**Comment by akutuzov** [comment]
Have you re-downloaded NorBERT?

**Comment by timpal0l** [comment]
> Have you re-downloaded NorBERT?

I believe so yes.
```
(simpletransformers) tim@gpu:~$ cd
(simpletransformers) tim@gpu:~$ cd .cache/
(simpletransformers) tim@gpu:~/.cache$ ls
huggingface
(simpletransformers) tim@gpu:~/.cache$ rm -rf huggingface/
```
There is nothing saved elsewhere to the best of my knowledge when downloading it from huggingface.

No difference when downloading it again.

**Comment by akutuzov** [comment]
The code below works perfectly for me. `train.csv` and `test.csv` are simple comma-separated text files with a binary label in the first column and a sentence in the second column. I am running it on a CPU, but  if need be, can test on a GPU as well. But it is highly unlikely this will make any difference.

```
from simpletransformers.classification import ClassificationModel, ClassificationArgs
import pandas as pd
import logging

logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)

train_data = pd.read_csv("train.csv")
test_data = pd.read_csv("test.csv")

train_data.columns = ["labels", "text"]
test_data.columns = ["labels", "text"]

model_args = ClassificationArgs(num_train_epochs=2)

model = ClassificationModel("bert", "ltgoslo/norbert", use_cuda=False, args=model_args)

model.train_model(train_data)

result, model_outputs, wrong_predictions = model.eval_model(test_data)

predictions, raw_outputs = model.predict(["Ny vokalist og ny start for norsk punks mest lovende ."])
print(predictions)
print(raw_outputs)
```

**Comment by timpal0l** [comment]
> The code below works perfectly for me. `train.csv` and `test.csv` are simple comma-separated text files with a binary label in the first column and a sentence in the second column. I am running it on a CPU, but if need be, can test on a GPU as well. But it is highly unlikely this will make any difference.
> 
> ```
> from simpletransformers.classification import ClassificationModel, ClassificationArgs
> import pandas as pd
> import logging
> 
> logging.basicConfig(level=logging.INFO)
> transformers_logger = logging.getLogger("transformers")
> transformers_logger.setLevel(logging.WARNING)
> 
> train_data = pd.read_csv("train.csv")
> test_data = pd.read_csv("test.csv")
> 
> train_data.columns = ["labels", "text"]
> test_data.columns = ["labels", "text"]
> 
> model_args = ClassificationArgs(num_train_epochs=2)
> 
> model = ClassificationModel("bert", "ltgoslo/norbert", use_cuda=False, args=model_args)
> 
> model.train_model(train_data)
> 
> result, model_outputs, wrong_predictions = model.eval_model(test_data)
> 
> predictions, raw_outputs = model.predict(["Ny vokalist og ny start for norsk punks mest lovende ."])
> print(predictions)
> print(raw_outputs)
> ```

Yes training on CPU seems to work. Would be great if it could work on GPU in the future.

Thanks!

**Comment by akutuzov** [comment]
So the same code does not work for you when running on a GPU, with everything else the same?

**Comment by timpal0l** [comment]
> So the same code does not work for you when running on a GPU, with everything else the same?

Exactly, it only works with `use_cuda=False`, if running on GPU, the loss is `nan`while training. Does it work for you? If you try on google colab or something..?

**Comment by akutuzov** [comment]
Confirmed, when running on GPU, `simpletransformers` fails to fine-tune. PyTorch issues this warning:
_UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate_

Looks like `simpletransformers` calls PyTorch in some incorrect way when using GPU. Not sure this is related to the NorBERT itself. 

In this repository you can find examples of it being used for [POS tagging](https://github.com/ltgoslo/NorBERT/blob/main/benchmarking/experiments/pos_finetuning.py) and [binary sentiment classification](https://github.com/ltgoslo/NorBERT/blob/main/benchmarking/experiments/sentiment_finetuning.py).  They do not use `simpletransformers` though.

Later I will look more into what the issue with `simpletransformers` can be about. For the time being, I guess you can just use `transformers` itself.

**Comment by akutuzov** [comment]
@timpal0l also note a similar issue here:
https://github.com/ThilinaRajapakse/simpletransformers/issues/983

**Comment by akutuzov** [comment]
If you find an answer to the GPU + `simpletransformers` issue before us, please drop a message here :)

By the way, the "vocabulary indices are not consecutive" error is [fixed](https://github.com/ltgoslo/NorBERT/commit/64568c3b4ee686b71d1643fbde7e23469c7e984c) now. It was caused by duplicate entries in the vocabulary. Now it makes even more sense to re-download the model from HuggingFace. 
Thanks for reporting this, much appreciated!

**Comment by akutuzov** [comment]
For reference @timpal0l , here is a minimal example of finetuning NorBERT for binary classification using raw PyTorch and Transformers:
https://github.com/ltgoslo/NorBERT/blob/main/utils/finetuning_example.py

Confirmed to work fine on a GPU.

**Comment by akutuzov** [comment]
Fixed  in the new NorBERT 2 model:
https://huggingface.co/ltgoslo/norbert2
