### ISSUE TITLE
Difference with nordic_bert? Thanks

### ISSUE THREAD

**Issue by junyongyou** [ltgoslo/NorBERT#2]
Excellent work. I guess the authors must be aware of nordic_bert (https://github.com/botxo/nordic_bert). Have you compared with that pretrained model? But at least one difference is that NorBERT is implemented in Torch, while nordic_bert is based on TensorFlow. Is that correct?

**Comment by akutuzov** [comment]
The model you mention is broken with regards to Norwegian: at least, we are not aware of anyone who successfully used it for any Norwegian NLP task. So it does not make sense to compare.

As for TF and PyTorch, not sure what you mean. NorBERT was trained using TensorFlow, but we provide the model in two variants.

There are many more details in our [paper](https://www.aclweb.org/anthology/2021.nodalida-main.4/), please check it!

**Comment by junyongyou** [comment]
> 
> 
> The model you mention is broken with regards to Norwegian: at least, we are not aware of anyone who successfully used it for any Norwegian NLP task. So it does not make sense to compare.
> 
> As for TF and PyTorch, not sure what you mean. NorBERT was trained using TensorFlow, but we provide the model in two variants.
> 
> There are many more details in our [paper](https://www.aclweb.org/anthology/2021.nodalida-main.4/), please check it!

Great that two variants were provided. Sorry I have not read your paper yet, will do it soon. Thanks a lot for the excellent work.
